// @no-log
DELETE localhost:8083/connectors/medium_debezium

###
// @no-log
GET localhost:8083/connectors/

###
// @no-log
# curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" kafka-connect:8083/connectors/ -d /conf/mysql_config.json
POST localhost:8083/connectors
Content-Type: application/json

{
  "name": "medium_debezium",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "mysql",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "debezium",
    "database.server.id": "184054",
    "database.server.name": "dbserver1",
    "database.include.list": "inventory",
    "database.history.kafka.bootstrap.servers": "kafka:9092",
    "database.history.kafka.topic": "schema-changes.inventory",
    "table.include.list": "customers, orders",
    "column.exclude.list": "inventory.customers.email",
    "topic.creation.default.replication.factor": 1,
    "topic.creation.default.partitions": 1,
    "topic.creation.default.compression.type": "lz4",
    "snapshot.mode": "initial",
    "snapshot.locking.mode": "none"
  }
}

###

